// Code generated by `go generate`. DO NOT EDIT.
// source: server/internal/gen/dispatch_gates_test.go.tmpl
package server

import "github.com/mark3labs/mcp-go/mcp"

// dispatchGates is the generator's table as the dispatch tests read it.
var dispatchGates = []dispatchGate{
	{method: mcp.MethodInitialize, removedInModern: true},
	{method: mcp.MethodPing, removedInModern: true},
	{method: mcp.MethodServerDiscover, requiresModern: true},
	{method: mcp.MethodSubscriptionsListen, requiresModern: true},
	{method: mcp.MethodSetLogLevel, capability: "logging", removedInModern: true},
	{method: mcp.MethodResourcesList, capability: "resources"},
	{method: mcp.MethodResourcesTemplatesList, capability: "resources"},
	{method: mcp.MethodResourcesRead, capability: "resources"},
	{method: mcp.MethodPromptsList, capability: "prompts"},
	{method: mcp.MethodPromptsGet, capability: "prompts"},
	{method: mcp.MethodToolsList, capability: "tools"},
	{method: mcp.MethodToolsCall, capability: "tools"},
	{method: mcp.MethodTasksGet, capability: "tasks"},
	{method: mcp.MethodTasksList, capability: "tasks", removedInModern: true},
	{method: mcp.MethodTasksResult, capability: "tasks", removedInModern: true},
	{method: mcp.MethodTasksCancel, capability: "tasks"},
	{method: mcp.MethodCompletionComplete, capability: "completions"},
}
